### ISSUE TITLE
[Feature] Adding `o200K_base` tokenizer to embed

### ISSUE THREAD

**Issue by mahimairaja** [andrew264/Smol-LM#1]
The new OpenAI model - omni is so remarkable. I guess the tokenizer is also a reason behind this powerful performance. Just curious to check if we could try this - [o200k_base Tokenizer](https://github.com/openai/tiktoken/blob/c0ba74c238d18b4824c25f3c27fc8698055b9a76/tiktoken/model.py#L9) with the Smol-LM 

Cheers!

**Comment by andrew264** [comment]
send a dozen of b100s for me to even try this 
kthxbye 🤗
