### ISSUE TITLE
GPT4o models

### ISSUE THREAD

**Issue by yukiarimo** [andrew264/Smol-LM#2]
Hey! Is it possible to make a small GPT4o-like model with native audio using the Smol-LM models?

**Comment by andrew264** [comment]
I am still experimenting with different native audio methods, and have not yet decided which one to use. In addition, the data and hardware required to train an LM are not currently feasible for me.

**Comment by yukiarimo** [comment]
I have a lot of speech data and infinite computing power. Can you please share even something, so I can try and experiment with multimodality?

**Comment by andrew264** [comment]
page 64 of `The Llama 3 Herd of Models` paper is a good start
